[package]
name = "storage"
version = "1.1.2"
edition = "2021"

[[bin]]
name = "storage"
path = "src/main.rs"

[dependencies]
fleet-storage = { path = "../../crates/fleet-storage" }
fleet-api = { path = "../../crates/fleet-api" }
fleet-core = { path = "../../crates/fleet-core" }
axum = "0.8.9"
axum-server = { version = "0.8.0", features = ["tls-rustls"] }
clap = "2.33.0"
config = { version = "0.14", default-features = false, features = ["toml", "json"] }
tokio = { version = "1.7.1", features = ["io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
tracing = "0.1.40"
tracing-subscriber = "0.2.3"
