[package]
name = "fleet-integration"
version = "1.1.2"
edition = "2021"

[dev-dependencies]
fleet = { path = "../fleet" }
bincode = "1.2.1"
hex = "0.4.2"
tokio = { version = "1.7.1", features = ["io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
tracing = "0.1.40"
tracing-futures = "0.2.3"
tw_chain = "1.1.3"
