[package]
name = "fleet-wallet"
version = "1.1.2"
edition = "2021"

[dependencies]
fleet-core = { path = "../fleet-core" }
tw_chain = "1.1.3"
tracing = "0.1.40"
serde = { version = "1.0.104", features = ["derive"] }
tokio = { version = "1.7.1", features = ["io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
hex = "0.4.2"
bincode = "1.2.1"
